name: CI Pipeline 

#PR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.14.0'
    
    - name: Install dependencies 
      run: |
        cd codebase/rdicidr-0.1.0
        npm install 

    - name: Install prettier 
      run: |
        cd codebase/rdicidr-0.1.0
        npm run prettier

    - name: test
      run: |
        cd codebase/rdicidr-0.1.0
        CI=true
        npm run test


    - name: build 
      run: |
        cd codebase/rdicidr-0.1.0
        npm run build 